package com.ai.assistance.operit.ui.common.composedsl

/**
 * AUTO-GENERATED from Compose Material3/Foundation component bindings.
 * Do not edit manually. Regenerate via tools/compose_dsl/generate_compose_dsl_artifacts.py.
 */
internal val composeDslGeneratedNodeRendererRegistry: Map<String, ComposeDslNodeRenderer> = mapOf(
    normalizeToken("Column") to { node, onAction, nodePath -> renderColumnNode(node, onAction, nodePath) },
    normalizeToken("Row") to { node, onAction, nodePath -> renderRowNode(node, onAction, nodePath) },
    normalizeToken("Box") to { node, onAction, nodePath -> renderBoxNode(node, onAction, nodePath) },
    normalizeToken("Spacer") to { node, onAction, nodePath -> renderSpacerNode(node, onAction, nodePath) },
    normalizeToken("LazyColumn") to { node, onAction, nodePath -> renderLazyColumnNode(node, onAction, nodePath) },
    normalizeToken("LazyRow") to { node, onAction, nodePath -> renderLazyRowNode(node, onAction, nodePath) },
    normalizeToken("Text") to { node, onAction, nodePath -> renderTextNode(node, onAction, nodePath) },
    normalizeToken("TextField") to { node, onAction, nodePath -> renderTextFieldNode(node, onAction, nodePath) },
    normalizeToken("Switch") to { node, onAction, nodePath -> renderSwitchNode(node, onAction, nodePath) },
    normalizeToken("Checkbox") to { node, onAction, nodePath -> renderCheckboxNode(node, onAction, nodePath) },
    normalizeToken("Button") to { node, onAction, nodePath -> renderButtonNode(node, onAction, nodePath) },
    normalizeToken("IconButton") to { node, onAction, nodePath -> renderIconButtonNode(node, onAction, nodePath) },
    normalizeToken("Card") to { node, onAction, nodePath -> renderCardNode(node, onAction, nodePath) },
    normalizeToken("MaterialTheme") to { node, onAction, nodePath -> renderMaterialThemeNode(node, onAction, nodePath) },
    normalizeToken("Surface") to { node, onAction, nodePath -> renderSurfaceNode(node, onAction, nodePath) },
    normalizeToken("Icon") to { node, onAction, nodePath -> renderIconNode(node, onAction, nodePath) },
    normalizeToken("LinearProgressIndicator") to { node, onAction, nodePath -> renderLinearProgressIndicatorNode(node, onAction, nodePath) },
    normalizeToken("CircularProgressIndicator") to { node, onAction, nodePath -> renderCircularProgressIndicatorNode(node, onAction, nodePath) },
    normalizeToken("SnackbarHost") to { node, onAction, nodePath -> renderSnackbarHostNode(node, onAction, nodePath) },
    normalizeToken("Badge") to { node, onAction, nodePath -> renderBadgeNode(node, onAction, nodePath) },
    normalizeToken("DismissibleDrawerSheet") to { node, onAction, nodePath -> renderDismissibleDrawerSheetNode(node, onAction, nodePath) },
    normalizeToken("Divider") to { node, onAction, nodePath -> renderDividerNode(node, onAction, nodePath) },
    normalizeToken("ElevatedButton") to { node, onAction, nodePath -> renderElevatedButtonNode(node, onAction, nodePath) },
    normalizeToken("ElevatedCard") to { node, onAction, nodePath -> renderElevatedCardNode(node, onAction, nodePath) },
    normalizeToken("ExtendedFloatingActionButton") to { node, onAction, nodePath -> renderExtendedFloatingActionButtonNode(node, onAction, nodePath) },
    normalizeToken("FilledIconButton") to { node, onAction, nodePath -> renderFilledIconButtonNode(node, onAction, nodePath) },
    normalizeToken("FilledIconToggleButton") to { node, onAction, nodePath -> renderFilledIconToggleButtonNode(node, onAction, nodePath) },
    normalizeToken("FilledTonalButton") to { node, onAction, nodePath -> renderFilledTonalButtonNode(node, onAction, nodePath) },
    normalizeToken("FilledTonalIconButton") to { node, onAction, nodePath -> renderFilledTonalIconButtonNode(node, onAction, nodePath) },
    normalizeToken("FilledTonalIconToggleButton") to { node, onAction, nodePath -> renderFilledTonalIconToggleButtonNode(node, onAction, nodePath) },
    normalizeToken("FloatingActionButton") to { node, onAction, nodePath -> renderFloatingActionButtonNode(node, onAction, nodePath) },
    normalizeToken("HorizontalDivider") to { node, onAction, nodePath -> renderHorizontalDividerNode(node, onAction, nodePath) },
    normalizeToken("IconToggleButton") to { node, onAction, nodePath -> renderIconToggleButtonNode(node, onAction, nodePath) },
    normalizeToken("LargeFloatingActionButton") to { node, onAction, nodePath -> renderLargeFloatingActionButtonNode(node, onAction, nodePath) },
    normalizeToken("ModalDrawerSheet") to { node, onAction, nodePath -> renderModalDrawerSheetNode(node, onAction, nodePath) },
    normalizeToken("ModalWideNavigationRail") to { node, onAction, nodePath -> renderModalWideNavigationRailNode(node, onAction, nodePath) },
    normalizeToken("NavigationBar") to { node, onAction, nodePath -> renderNavigationBarNode(node, onAction, nodePath) },
    normalizeToken("NavigationRail") to { node, onAction, nodePath -> renderNavigationRailNode(node, onAction, nodePath) },
    normalizeToken("OutlinedButton") to { node, onAction, nodePath -> renderOutlinedButtonNode(node, onAction, nodePath) },
    normalizeToken("OutlinedCard") to { node, onAction, nodePath -> renderOutlinedCardNode(node, onAction, nodePath) },
    normalizeToken("OutlinedIconButton") to { node, onAction, nodePath -> renderOutlinedIconButtonNode(node, onAction, nodePath) },
    normalizeToken("OutlinedIconToggleButton") to { node, onAction, nodePath -> renderOutlinedIconToggleButtonNode(node, onAction, nodePath) },
    normalizeToken("PermanentDrawerSheet") to { node, onAction, nodePath -> renderPermanentDrawerSheetNode(node, onAction, nodePath) },
    normalizeToken("ProvideTextStyle") to { node, onAction, nodePath -> renderProvideTextStyleNode(node, onAction, nodePath) },
    normalizeToken("Scaffold") to { node, onAction, nodePath -> renderScaffoldNode(node, onAction, nodePath) },
    normalizeToken("ShortNavigationBar") to { node, onAction, nodePath -> renderShortNavigationBarNode(node, onAction, nodePath) },
    normalizeToken("SmallFloatingActionButton") to { node, onAction, nodePath -> renderSmallFloatingActionButtonNode(node, onAction, nodePath) },
    normalizeToken("Snackbar") to { node, onAction, nodePath -> renderSnackbarNode(node, onAction, nodePath) },
    normalizeToken("Tab") to { node, onAction, nodePath -> renderTabNode(node, onAction, nodePath) },
    normalizeToken("TextButton") to { node, onAction, nodePath -> renderTextButtonNode(node, onAction, nodePath) },
    normalizeToken("VerticalDivider") to { node, onAction, nodePath -> renderVerticalDividerNode(node, onAction, nodePath) },
    normalizeToken("VerticalDragHandle") to { node, onAction, nodePath -> renderVerticalDragHandleNode(node, onAction, nodePath) },
    normalizeToken("WideNavigationRail") to { node, onAction, nodePath -> renderWideNavigationRailNode(node, onAction, nodePath) },
    normalizeToken("BoxWithConstraints") to { node, onAction, nodePath -> renderBoxWithConstraintsNode(node, onAction, nodePath) },
    normalizeToken("BasicText") to { node, onAction, nodePath -> renderBasicTextNode(node, onAction, nodePath) },
    normalizeToken("DisableSelection") to { node, onAction, nodePath -> renderDisableSelectionNode(node, onAction, nodePath) },
    normalizeToken("Image") to { node, onAction, nodePath -> renderImageNode(node, onAction, nodePath) },
    normalizeToken("SelectionContainer") to { node, onAction, nodePath -> renderSelectionContainerNode(node, onAction, nodePath) }
)
