/** 1:1 对齐 hermes/gateway/platforms/qqbot/crypto.py */
package com.xiaomo.hermes.hermes.gateway.platforms.qqbot

import android.util.Base64
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * AES-256-GCM utilities for QQBot scan-to-configure credential decryption.
 */
object Crypto {

    /**
     * Generate a 256-bit random AES key and return it as base64.
     *
     * The key is passed to `create_bind_task` so the server can encrypt
     * the bot's client_secret before returning it. Only this client holds
     * the key, ensuring the secret never travels in plaintext.
     */
    fun generateBindKey(): String {
        val key = ByteArray(32)
        SecureRandom().nextBytes(key)
        return Base64.encodeToString(key, Base64.NO_WRAP)
    }

    /**
     * Decrypt a base64-encoded AES-256-GCM ciphertext.
     *
     * Ciphertext layout (after base64-decoding):
     *     IV (12 bytes) ‖ ciphertext (N bytes) ‖ AuthTag (16 bytes)
     *
     * @param encryptedBase64 The `bot_encrypt_secret` value from `poll_bind_result`.
     * @param keyBase64 The base64 AES key generated by [generateBindKey].
     * @return The decrypted client_secret as a UTF-8 string.
     */
    fun decryptSecret(encryptedBase64: String, keyBase64: String): String {
        val key = Base64.decode(keyBase64, Base64.NO_WRAP)
        val raw = Base64.decode(encryptedBase64, Base64.NO_WRAP)

        val iv = raw.copyOfRange(0, 12)
        val ciphertextWithTag = raw.copyOfRange(12, raw.size)

        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        val keySpec = SecretKeySpec(key, "AES")
        val gcmSpec = GCMParameterSpec(128, iv) // 128-bit auth tag
        cipher.init(Cipher.DECRYPT_MODE, keySpec, gcmSpec)

        val plaintext = cipher.doFinal(ciphertextWithTag)
        return String(plaintext, Charsets.UTF_8)
    }
}
